### ISSUE TITLE
I feel you mean "active window" instead of "focused one"

### ISSUE THREAD

**Issue by fboumol** [astier/xfocusnotify#1]
Thanks for this software. It works great in my multimonitor setup with xmonad (as window manager).

My setup is a bit special (because I always prefer keyboard approaches) in the sense that my xmonad configuration does not change the active window when I move the mouse outside the active window. In other words, it allows that the active window is not the focused one (with the term focused I refer to the window where the mouse is).

In such case, I can confirm you that your software gives information about the active window (which is indeed what I prefer) and not about the focused one. Perhaps you can clarify this in the readme to avoid misinterpretations (since the name of your program might suggest it deals with "focus").

**Comment by astier** [comment]
### Short answer

 I guess we have a misunderstanding what constitutes a focused and active window. Short answer:

- Generally `keyboard-input == focus == active`
- If wm changes focus when mouse enters new window then: `mouse = focus = active`
- If wm doesn't change focus when mouse enters new window then: `mouse != focus` and `active = focus`

>my xmonad configuration does not change the active window when I move the mouse outside the active window

In that case it also shouldn't change the focus.

>it allows that the active window is not the focused one (with the term focused I refer to the window where the mouse is)

Mouse doesn't equal focus necessarily (read long answer for explanation). Either xmonad changes the focus when the mouse enters another window, in which case _NET_ACTIVE_WINDOW should be changed to that window, or xmonad keeps the focus  on the same window even though the mouse enters another window, in which case _NET_ACTIVE_WINDOW shouldn't change.

### Long answer

Based on my understanding a **window is focused** if the keyboard is attached to this window ([source](https://tronche.com/gui/x/xlib/events/input-focus/)). Meaning all the keyboard input goes do that specific window (although it can be intercepted by other clients which manage your hotkeys like your wm or hotkey-daemons like sxhkd). It is not defined by where the mouse points to.

Some window-managers have a **focus-follows-mouse feature** which means that whenever the mouse enters a window it sets the focus to that window (in C by calling [XSetInputFocus](https://tronche.com/gui/x/xlib/input/XSetInputFocus.html) on that window). Meaning all the keyboard-input goes from now on to that window. That however is a wm-specific behavior and is not the default behavior of X. The wm can do whatever it wants when the mouse enters another window. It's up to the developers.

The **active window**, as I understand, is just the focused window (well not always actually, read more [here](https://stackoverflow.com/questions/31800880/xlib-difference-between-net-active-window-and-xgetinputfocus), on the low-level it might not be the same window but logically it should be the window which your wm is pretending to give focus). Again it doesn't follow mouse but rather the input-focus.

If xmonad changes the focus (and therefore the keyboard-input) to the window where the mouse points to by calling XSetInputFocus on that window, than _NET_ACTIVE_WINDOW should also be set to that window. If xmonad keeps the focus on a window even though the mouse enters another window than also _NET_ACTIVE_WINDOW shouldn't change.

For clarification. [_NET_ACTIVE_WINDOW](https://specifications.freedesktop.org/wm-spec/latest/ar01s03.html#idm45539547170400) is just a convention which a wm SHOULD follow if it wants that other programs which rely on _NET_ACTIVE_WINDOW work properly. The wm doesn't have to set _NET_ACTIVE_WINDOW. Or it can set it to whatever it wants. Again it's up to the developers of the wm.

**Comment by astier** [comment]
https://tronche.com/gui/x/xlib/events/input-focus/

> The keyboard is always attached to some window (typically, the root window or a top-level window), which is called the focus window. The focus window and the position of the pointer determine the window that receives keyboard input.

**Comment by astier** [comment]
Long story short the active window is the focused window. If they are not the same the wm is doing something wrong. I think the issue here is that you think that the focused window is defined by where the mouse points to. Which can happen but then _NET_ACTIVE_WINDOW has to be set to the window under the mouse. But maybe I misunderstand something here.

**Comment by astier** [comment]
Besides that does the program solve your problem or do you need to know when your mouse enters a new window? For this there is the so called [EnterNotify](https://tronche.com/gui/x/xlib/events/window-entry-exit/)-event.

**Comment by fboumol** [comment]
astier, everything is fine. 

I just wrote my remark because it took me some time to realize why the program was not following, in my settings, the mouse. This was due to my confusion between active and focus windows. After reading the previous comments it seems pretty clear I was on the minority side (and now I know you are indeed following the tradition of X11 documentation).

**Comment by astier** [comment]
Glad everything is fine.
